agora_game_puissance4:
    resource: "@AGORAGamePuissance4Bundle/Resources/config/routing.yml"
    prefix:   /game/puissance4

agora_game_azul:
    resource: "@AGORAGameAzulBundle/Resources/config/routing.yml"
    prefix:   /game/azul

agora_game_rr:
    resource: "@AGORAGameRRBundle/Resources/config/routing.yml"
    prefix:   /game/rr

agora_game_morpion:
    resource: "@AGORAGameMorpionBundle/Resources/config/routing.yml"
    prefix:   /game/morpion

agora_game_splendor:
    resource: "@AGORAGameSplendorBundle/Resources/config/routing.yml"
    prefix:   /

agora_game_game:
    resource: "@AGORAGameGameBundle/Resources/config/routing.yml"
    prefix:   /game/game

agora_game_ave_cesar:
    resource: "@AGORAGameAveCesarBundle/Resources/config/routing.yml"
    prefix:   /game/avecesar

agora_game_sqp:
    resource: "@AGORAGameSQPBundle/Resources/config/routing.yml"
    prefix:   /game/sqp

augustus:
    resource: "@AugustusBundle/Resources/config/routing.yml"
    prefix:   /game/augustus

agora_admin_platform:
    resource: "@AGORAAdminPlatformBundle/Resources/config/routing.yml"
    prefix:   /admin

agora_platform:
    resource: "@AGORAPlatformBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
