agora_platform_homepage:
    path: /
    defaults: { _controller: AGORAPlatformBundle:Default:index }

agora_platform_project:
    path: /project
    defaults: { _controller: AGORAPlatformBundle:Default:theProject }

agora_platform_profile:
    path: /profile
    defaults: { _controller: AGORAPlatformBundle:Default:profile }

agora_platform_contact:
    path: /contact
    defaults: { _controller: AGORAPlatformBundle:Default:contact }

agora_platform_gamelist:
    path: /gamelist/{game}
    defaults: { _controller: AGORAPlatformBundle:Default:gameList, game: "*" }

agora_platform_gamelist_create:
    path: /gamelistcreate
    defaults: { _controller: AGORAPlatformBundle:Default:gameListCreate, game: "*" }


agora_platform_leaderboard:
    path: /leaderboard/{game}
    defaults: { _controller: AGORAPlatformBundle:Default:leaderboard, game: "*" }

agora_platform_game_create:
    path: /game/create/{gameId}
    defaults: { _controller: AGORAPlatformBundle:Default:createGame, gameId: "" }


agora_platform_joingame:
    path: /joingame
    defaults: { _controller: AGORAPlatformBundle:Default:joinGame, gameId: "" }

agora_platform_playerParties:
    path: /playerparties/{userId}
    defaults: { _controller: AGORAPlatformBundle:Default:playerParties }    

agora_platform_moderation:
    path: /moderation
    defaults: { _controller: AGORAPlatformBundle:Default:moderation }    

